[package]
name = "pong-rl"
version = "0.1.0"
edition = "2021"

[lib]
name = "pong_rl"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "pong_rl_game"
path = "src/main.rs"

[dependencies]
pixels = "0.13.0"
pyo3 = { version = "0.19.2", features = ["extension-module"] }
rand = "0.8.5"
winit = "0.27.1"